### ISSUE TITLE
Strange authentication issue

### ISSUE THREAD

**Issue by umamiking** [deadcyclo/narrative-ripper#3]
Mac OS X Sierra
Python 2.7.10

When I run ripper and supply it the client id, client secret, and path (should this end in a slash or not?), I get the oauth screen open in my browser but it's either an empty screen or it says authentication failed. Then, when I refresh the page, it seems to find the server on localport and I get this

`127.0.0.1 - - [10/Oct/2016 14:34:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2016 14:34:11] code 404, message File not found
127.0.0.1 - - [10/Oct/2016 14:34:11] "GET /favicon.ico HTTP/1.1" 404 -`

Then it just sits there. I quit out of it and tried running the script again but it complained that the server was already running on that port. How can I fix this? And how can I kill the currently running server so it frees up the port?

**Comment by deadcyclo** [comment]
You should be getting a page asking you to authorize the application to access your data. A blank page sounds like an issue at narratives end. 
Several people have reported that the Narrative servers have been very unstable today especially their authorization servers. 

I. Would wait a little bit and try again later if I were you. Hopefully their servers will be working again soon. 

You should be able to enter the path with or without a training slash. It shouldn't matter.

**Comment by deadcyclo** [comment]
I just got a great patch from Nils Hamerlinck that enables using email and password to log on, rather than oauth 2 key/secret. Please download the latest version and try again, let me know if you have any issues. Note that during testing the patch, I discovered that the Narrative API is really really slow at the moment, so have patience, I guess their servers are very overloaded at the moment. I'm going ahead and closing this issue.
