### ISSUE TITLE
Hard CPU loop

### ISSUE THREAD

**Issue by pjsg** [deadcyclo/narrative-ripper#4]
The ripper uses 100% of the CPU on linux. I suspect that this is the oauth thread trying to restart the listener. I worked around the problem by grabbing the token and hard coding it in the ripper script and not calling the oauth code at all. Things are now running (albeit slowly).

**Comment by deadcyclo** [comment]
Interesting. I didn't have any issues with that (but I did grab the token as you did, simply because I didn't want to have to re-authorize ever single time I ran the script during development).

Yeah. The Narrative API is really slow. Grabbing my metadata took almost as long as grabbing my content. Once you have the metadata and run the downloader things should speed up greatly.

**Comment by deadcyclo** [comment]
I just got a great patch from Nils Hamerlinck that enables using email and password to log on, rather than oauth 2 key/secret. Please download the latest version and try again, let me know if you have any issues. Note that during testing the patch, I discovered that the Narrative API is really really slow at the moment, so have patience, I guess their servers are very overloaded at the moment. I'm going ahead and closing this issue.

**Comment by pjsg** [comment]
My fetching is chugging along -- I'm on page 2 of moments! I'm really interested in the exif tag and geoloc for these images. [I did add the exif rotation data to he images that I saved locally, but I never had the geoloc data.]

**Comment by deadcyclo** [comment]
I am as well. Unfortunately It seems I'm going to be very busy the next couple of weeks so I most likely will not be able to make a tool until after the next couple of weeks. But I most definitely want to make a tool for it. Just make sure you keep both your images and metadata intact in the same folder structure as they are downloaded in, and any tool I make should work fine ;)

Btw. Do you have google location history turned on on your phone. The Narrative location data is sketchy at best, and one of my ideas is to make a tool to interpolate it with data exported from google location history for better accuracy.
